model:
  n_position: 1024
  embed_dim: 768
  hidden_dim: 1024
  num_heads: 6
  n_layers: 8
  dropout_prob: 0.1

training:
  batch_size: 64
  learning_rate: 5e-5
  epochs: 5
  max_seq_len: 128

data:
  dataset_path: "data/base"
  validation_split: 0.1