model:
  n_position: 128
  embed_dim: 192
  hidden_dim: 128
  num_heads: 6
  n_layers: 3
  dropout_prob: 0.1

training:
  batch_size: 64
  learning_rate: 1e-4
  epochs: 3
  max_seq_len: 128

data:
  dataset_path: "data/test"
  validation_split: 0.1