model:
  n_position: 1024
  embed_dim: 256
  hidden_dim: 512
  num_heads: 4
  n_layers: 4
  dropout_prob: 0.1

training:
  batch_size: 32
  learning_rate: 1e-4
  epochs: 8
  max_seq_len: 64

data:
  dataset_path: "data/plwiki"
  validation_split: 0.1